sbatch experiments/E69-search-limited-fov/foragax/ForagaxTwoBiome-v10/process_data_job.sh
sbatch experiments/E70-mitigations/foragax/ForagaxTwoBiome-v10/process_data_job.sh
sbatch experiments/E71-baselines-vs-recurrent/foragax/ForagaxTwoBiome-v10/process_data_job.sh
sbatch experiments/E73-search-limited-fov/foragax/ForagaxTwoBiome-v10/process_data_job.sh
sbatch experiments/E74-mitigations/foragax/ForagaxTwoBiome-v10/process_data_job.sh
sbatch experiments/E75-baselines-vs-recurrent/foragax/ForagaxTwoBiome-v10/process_data_job.sh
sbatch experiments/E76-search-limited-fov/foragax/ForagaxTwoBiome-v13/process_data_job.sh
sbatch experiments/E77-mitigations/foragax/ForagaxTwoBiome-v13/process_data_job.sh
sbatch experiments/E78-baselines-vs-recurrent/foragax/ForagaxTwoBiome-v13/process_data_job.sh
sbatch experiments/E79-search-limited-fov/foragax/ForagaxTwoBiome-v14/process_data_job.sh
sbatch experiments/E80-mitigations/foragax/ForagaxTwoBiome-v14/process_data_job.sh
sbatch experiments/E81-baselines-vs-recurrent/foragax/ForagaxTwoBiome-v14/process_data_job.sh
sbatch experiments/E82-search-limited-fov/foragax/ForagaxTwoBiome-v15/process_data_job.sh
sbatch experiments/E83-mitigations/foragax/ForagaxTwoBiome-v15/process_data_job.sh
sbatch experiments/E84-baselines-vs-recurrent/foragax/ForagaxTwoBiome-v15/process_data_job.sh
sbatch experiments/E85-search-limited-fov/foragax/ForagaxTwoBiome-v16/process_data_job.sh
sbatch experiments/E86-mitigations/foragax/ForagaxTwoBiome-v16/process_data_job.sh
sbatch experiments/E87-baselines-vs-recurrent/foragax/ForagaxTwoBiome-v16/process_data_job.sh
